config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"

  resources :items do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: "選択" }, { id: 2, name: "食事"},
    { id: 3, name: "睡眠" }, { id: 4, name: "投資"},
    { id: 5, name: "リーダーシップ" }, { id: 6, name: "ロジカルシンキング"} ,
    { id: 7, name: "心理学" }, { id: 8, name: "脳科学" },
    { id: 9, name: "ビジネス" }, { id: 10, name: "子育て" }
  ]
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :itemtags, dependent: :destroy
  has_many :tags, through: :itemtags
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category


end

app/models/itemtag.rb
class Itemtag < ApplicationRecord

  belongs_to :item
  belongs_to :tag
  
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :itemtags
  has_many :items, through: :itemtags

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :search_item
  before_action :category_set

  def index
    @items = Item.all.order(created_at: :desc).last(6)
    @item_count = Item.count
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = ItemsTag.new
  end

  def create
    @item = ItemsTag.new(itemtag_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path
    else 
      render "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    binding.pry
    if @item.destroy
      redirect_to root_path
    else
      render "show"
    end
  end

  def search
    @results = @p.result
  end

  private

  def itemtag_params
    params.require(:items_tag).permit(:title, :image, :author, :text, :category_id)
    params.require(:items_tag).permit(:name).split(nil)
  end

  def item_params
    params.require(:item).permit(:title, :image, :author, :text, :category_id)
  end

  def search_item
    @p = Item.ransack(params[:q])
  end

  def category_set
    @category = Category.where.not(id: 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render 'shared/header' %>

<div class="items">
<div class="new">
<%= form_with model: @item, class:"item-new", local: true do |f| %>
  <div class="item-input">
    <b>タイトル</b>
  </div>
    <%= f.text_field :title, class:"field-input" %>
  <div class="item-input">
    <b>画像</b>
  </div>
    <%= f.label :image, for:"image-new", class:"item-image-label" do %>
      選択する
      <%= f.file_field :image, class:"image-new", id:"image-new", style:"display: none;" %>
    <% end %>
  <div class="item-input">
    <b>著者（またはyoutube）</b>
  </div>
    <%= f.text_field :author, class:"field-input" %>
  <div class="item-input">
    <b>メモ</b>
  </div>
    <%= f.text_area :text, class:"area-input" %>
  <div class="item-input">
    <b>カテゴリー</b>
  </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"item-select"}) %>
  <div class="item-input">
    <b>タグ<b>
  </div>
    <%= f.text_field :name, class:"field-input" %>
  <div>
    <b><%= f.submit "保存", class:"new-link" %></b>
  </div>
  <% end %>
</div>
</div>

app/views/items/index.html.erb
<%= render 'shared/header' %>
<div class="items">
  <div class="items-inner">
    <ul class="item-list">
      <% @items.each do |item| %>
        <li>
          <%= link_to item_path(item.id) do %>
            <%= image_tag item.image, class:"item-image" %>
            <div class="item-title">
              <%= item.title %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/new.html.erb
<%= render 'shared/header' %>

<div class="items">
<div class="new">
<%= form_with model: @item, url: items_path, class:"item-new", local: true do |f| %>
  <div class="item-input">
    <b>タイトル</b>
  </div>
    <%= f.text_field :title, class:"field-input" %>
  <div class="item-input">
    <b>画像</b>
  </div>
    <%= f.label :image, for:"image-new", class:"item-image-label" do %>
      選択する
      <%= f.file_field :image, class:"image-new", id:"image-new", style:"display: none;" %>
    <% end %>
  <div class="item-input">
    <b>著者（またはyoutube）</b>
  </div>
    <%= f.text_field :author, class:"field-input" %>
  <div class="item-input">
    <b>メモ</b>
  </div>
    <%= f.text_area :text, class:"area-input" %>
  <div class="item-input">
    <b>カテゴリー</b>
  </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"item-select"}) %>
  <div class="item-input">
    <b>タグ<b>
  </div>
    <%= f.text_field :name, class:"field-input" %>
  <div>
    <b><%= f.submit "保存", class:"new-link" %></b>
  </div>
  <% end %>
</div>
</div>

app/views/items/search.html.erb
<%= render 'shared/header' %>

<div class="items">
  <div class="items-inner">
    <ul class="item-list">
      <% @results.each do |result| %>
        <li>
          <%= link_to item_path(result.id) do %>
            <%= image_tag result.image, class:"item-image" %>
            <div class="item-title">
              <%= result.title %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/show.html.erb
<%= render 'shared/header' %>

<div class="items">
<div class="item-show">
  <div class="show-edit-link">
    <%= link_to "編集", edit_item_path, class:"edit-link" %>
    <%= link_to "削除", item_path(@item), method: :delete, class:"edit-link" %>
  </div>
  <div class="item-top">
    <div class="item-top-image">
      <%= image_tag @item.image, class:"show-image"%>
    </div>
    <div class="item-top-right">
      <div class="item-info">
        <b>タイトル</b>
      </div>
      <%= @item.title %>
      <div class="item-info">
        <b>著者</b>
      </div>
      <%= @item.author %>
      <div class="item-info">
        <b>カテゴリー</b>
      </div>
      <%= @item.category.name %>
      <div class="item-info">
        <b>登録日</b>
      </div>
      <%= @item.created_at.strftime("%Y.%m.%d") %>
    </div>
  </div>
  <div class="item-bottom">
    <div class="item-memo">
      <b>メモ</b>
    </div>
    <%= simple_format(@item.text) %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="wrapper">
  <div class="wrapper-inner">
    <div>
      <%= link_to root_path do %>
        <i class="fa fa-home fa-2x" aria-hidden="true"></i>
      <% end %>
      <b>total：<%= Item.count %></b>
    </div>
    <div>
      <%= link_to  new_item_path do %>
        <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
      <% end %>
      <i class="fa fa-list-ul fa-2x" aria-hidden="true" id="lists"></i>
        <ul class="category hidden" id="pull-down">
          <% @category.each do |category| %>
            <%= link_to search_items_path(@p, :'q[category_id_eq' => "#{category.id}"), class:"category-list" do %>
              <li><%= category.name %></li>
            <% end %>
          <% end %>
        </ul>
      <i class="fa fa-th fa-2x" aria-hidden="true"></i>
    </div>
  </div>
</div>